### PR TITLE
Optionally load the  map from Google's Chinese servers.

### PR DESCRIPTION
**Pull request by monsieurmechant**
Hey Guillaume,

first of all thanks a lot for the component, it's awesome. We're using it in production [here](http://www.certina.com/customer-service), I can't begin to tell you how much time it saved me!

We do have one problem on the Chinese version though. To display a Google Map in mainland China, we need to [load it from a different url](https://developers.google.com/maps/documentation/javascript/basics#GoogleMapsChina), and I could not find a way to do it through the existing component options.

The pull request adds a new `loadCn` parameter  to the manager `load` function. If set to `true` the map will be loaded from google maps China.

Tell me what you think.

Thanks again.
Adam.

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Thank you for feedback. Glad someone else using it in production too ! 

Your PR looks great but sadly I can't merge it because there is a conflict. Can you fix it. I'll merge it as soon as I can.

**Comment by monsieurmechant** [comment]
Done. The conflict was on the compiled files :+1: .

**Comment by GuillaumeLeclerc** [comment]
thank you

**Comment by GuillaumeLeclerc** [comment]
Published under v0.1.15

**Comment by monsieurmechant** [comment]
Great! Merci beaucoup :smiley:

**Pull request merged**
