### PR TITLE
Standardize how MapComponents are created

### PR DESCRIPTION
**Pull request by xkjyeah**
In this PR, every component inherits from MapComponent (`MapComponent.extend({...})`).

MapComponent provides a `$mapPromise` and a `$map` property. In the `ready()` handler of MapComponent, it dispatches the `register-component` event. When this event is received by the map container, it emits the `map-ready` event on the child. MapComponent responds to the `map-ready` event by resolving `$mapPromise`.

Components that require a google.maps.Map object should wait on `$mapPromise` before initializing their google maps components.

By extending `MapComponent`, a user can create new components (e.g. HeatMaps, Overlays). An example (Ground Overlay) has been provided. This example is not idiomatic -- it does not use eventBinding or propBinding, but suffices to demonstrate how child components can get access to their Google Map object via `vm.$map`.

In addition to `$map`, components' `*Object` properties have been renamed to `$*Object` in the more idiomatic Vue way to avoid conflicts with data properties of the same name.

### CODE REVIEW

**Comment by xkjyeah** [comment]
Components that may have parent components other than the Map component (e.g. `Marker --> InfoWindow`) should dispatch a *second* event (e.g. `register-infoWindow`) when initialized. The parent component will intercept this event and process accordingly.

**Comment by GuillaumeLeclerc** [comment]
If I understood well your PR solves the problem only for map. If I want to create new component `foo` that is a child of a `marker` I can't make it because marker needs to send a `register-foo` event and is not doing so right ?

**Comment by xkjyeah** [comment]
We could create a subclass of a marker (Marker.extend(...)) and add a
register-foo event listener. This subclass of Marker should then reply with
a marker-ready event. This is how I implemented InfoWindow in this PR.

That said, mixins sound like a cleaner approach. I could mix in a “position
provider” into Markers, Circles etc. but I haven't explored Vue's mixin API.

**Comment by GuillaumeLeclerc** [comment]
I think `MarkerProvider` instead of position might be a better idea since the child might want to access the underlying google maps object but your actual solution seems fine. 

Have you tested it with the vue-google-maps example or I have to do it before merging ? 

Thank you for your job.

**Comment by xkjyeah** [comment]
Well I guess the point is if too many components require a marker provider
then we create such a MarkerProvider class and a MarkerConsumer mixin.
Until then, I don't see the need to overengineer an Angular-like dependency
injection mechanism.

I did some tests on my own but they are not as extensive as your examples.
Basically everything seemed to plot fine. I'd say that you should do some
tests too...

**Comment by GuillaumeLeclerc** [comment]
Sorry for the delay. I'll be testing it tonight

**Comment by GuillaumeLeclerc** [comment]
I tested your PR on `vue-google-maps-example` and about half of the features are broken. I hope you understand I can't merge it, A lot of users would complain about it.

**Comment by xkjyeah** [comment]
No problem. Because you don't have automated tests, do you have a list of
features that should be tested on the examples?

**Comment by GuillaumeLeclerc** [comment]
To test, I just run `vue-google-maps-example` with the version I want to test. I know there are no tests right now but really don't have time to add them. I try to maintain this repository as good as I can with the little amount of time I have. If you can add them I'd accept a PR of course.

**Pull request closed without merging**
