### PR TITLE
Small change to allow complex polygons

### PR DESCRIPTION
**Pull request by Bre77**
The use of setPath only "Sets the first path", where as setPaths "Sets the path for this polygon." It seems no functionality is lost by using setPaths, but it allows you to setup complex polygons defined by arrays of arrays.

See https://developers.google.com/maps/documentation/javascript/3.exp/reference#Polygon

Note: I have confirmed this change doesn't break current functionality, but it still doesn't seem to have the fully desired effect. It should however be a step in the right direction.

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Is the two way binding still working. I have doubts about it since you don't watch the result of `getPaths()` as I do with `getPath()`

**Comment by Bre77** [comment]
Added those in and did some testing, looks like it works. I haven't tried editing though. My demo is at: http://map.ba.id.au/dropdown.html

There is still an issue when _creating_ a polygon with a complex path. If you create the polygon with no path, then add a path it works, but if you use a v-if and create the polygon after the path has been defined, it somehow uses the setpath method internally which will fail. This doesn't however affect simple paths at all.
setpath

**Comment by GuillaumeLeclerc** [comment]
Can you try editing before I merge because I'm not sure it will work.

**Comment by GuillaumeLeclerc** [comment]
I took a deeper look at how you are trying to achieve this.

First I don't get why there is no paths property in the vue component. Vue google maps should be as close as the google maps api. So if your PR supports complex paths then it should have a `paths` property to mimic the Google api. This is what could cause your error.

I also think we should watch both `getPath` and `getPaths` since a user should be able to use complex or simple polygons.

**Comment by Bre77** [comment]
I will try editing and get back to you.

I don't believe there is a "paths" property, it just uses path, the same as polyline. I do understand what you mean though, and will look into that further.

As far as I understand the Google Maps API, getPaths will still return the single path if the user is using a simple polygon, but getPath will only return the first polygon, so getPaths should be the right approach here for watching.

**Comment by GuillaumeLeclerc** [comment]
I'm sorry but if you look at the google maps reference there is: `getPath`, `getPaths`, `setPath` and `setPaths`. And as I'm trying to stick to the Google API as close as possible there must be `path` and `paths` props. The aim of this is if someone reads the google documentation he can use `vue-google-maps` without having to read the `vue-google-maps` documentation.

**Comment by Bre77** [comment]
Well I'll be, I was not aware of the 'paths' property, this is most certainly the cause of my issue. I will take your suggestion and build a seperate 'paths' property.

**Comment by GuillaumeLeclerc** [comment]
As a general rule of thumb I'm using to decide what are the properies of components I do this:

- If it there is `getXxxx` or `setXxxx` method on the underlying object then there is a property called xxxx in the component
- If there is a `xxxx_changed` event or any other way to know when the `getXxxx` would return a different value, the property is two way
- If there is now `getXxxx` then I make them "two-way-reversed", that means write to to model are ignored.
- An exception is made if there is no `setXxxx` and no way to know when the `getXxxx` will return a different value I disable the property and wait from someone that really needs this getter.

**Pull request closed without merging**
