### PR TITLE
resize-map event listener

### PR DESCRIPTION
**Pull request by smartpierre**
This is a small addition that allows the map component to listen to a event from a parent asking for a resize.

For example : when your map is hidden and you want to show it, the map will not show the tiles, you have to send an event to the map element so it can be properly resized.

See : http://stackoverflow.com/questions/4064275/how-to-deal-with-google-map-inside-of-a-hidden-div-updated-picture

### CODE REVIEW

**Comment by smartpierre** [comment]
However, on resize, the center of the map is not set properly, but I don't know what's the best way to do it. Any idea ?

**Comment by GuillaumeLeclerc** [comment]
For the center, can you just get the correct center from the the model and update the google maps object ?

**Comment by smartpierre** [comment]
updated :)

**Comment by GuillaumeLeclerc** [comment]
Does it work fine with the center set now ?

**Comment by smartpierre** [comment]
I tested it, it works great, try it for yourself if you have a few minutes :)

**Comment by GuillaumeLeclerc** [comment]
Thank you !

**Pull request merged**
